### PR TITLE
SAMZA-2433: Use log4j2 in samza-hello-samza

### PR DESCRIPTION
**Pull request by cameronlee314**
Issues: Log4j v1 is EOL and log4j2 is generally more performant and has a better module structure. Also, it is easier to handle split deployment functionality when using log4j2.

Changes:
Removed log4j v1 dependencies and added log4j2 dependencies (for both Gradle and Maven)
Added log4j2.xml and removed log4j.xml
Cleaned up some of the dependency specifications in order to make it easier to properly exclude log4j1 and include log4j2

Tests: Ran WikipediaApplication for a Gradle build and for a Maven build; verified that the logs showed up properly and that the job had output data.

API Changes: None

Upgrade Instructions: None

Usage Instructions: No changes to existing build/deployment flows

### CODE REVIEW

**Comment by prateekm** [comment]
@PawasChhokra Can you take a look as well?

**Comment by prateekm** [comment]
@cameronlee314 does this mean that we'd require jobs to upgrade to log4j2 as well?

**Comment by cameronlee314** [comment]
> @cameronlee314 does this mean that we'd require jobs to upgrade to log4j2 as well?

No, it is not required for jobs to upgrade to log4j2. If not using split deployment, then both log4j v1 and v2 would continue to work as is. If using split deployment, then the split deployment framework package determines whether log4j v1 or v2 needs to be used by a job (although I have currently only prototyped supporting log4j2).

**Comment by cameronlee314** [comment]
To clarify a bit further in the split deployment case: If a job is set up to use log4j2 in the non-split-deployment case, then it will still work in the split deployment case if the split deployment framework is set up for log4j2.
The impact of split deployment is that a particular framework package can only support one of log4j v1 or v2 as the slf4j binding.

**Pull request merged**
